"""adds Board and Card models

Revision ID: 743986718b3d
Revises: 
Create Date: 2023-01-03 11:18:47.094011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743986718b3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'title')
    op.drop_column('board', 'owner')
    op.drop_column('card', 'color')
    op.drop_column('card', 'likes_count')
    op.drop_column('card', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('card', sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('card', sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('board', sa.Column('owner', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('board', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
