"""empty message

Revision ID: a35c7424a422
Revises: c4c6917040c6
Create Date: 2023-01-03 17:56:18.819525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35c7424a422'
down_revision = 'c4c6917040c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('board', 'board')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('board', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('board', 'title')
    # ### end Alembic commands ###
