"""empty message

Revision ID: c4a672c1a2d2
Revises: 42155d349dbe
Create Date: 2023-01-04 20:06:52.804143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a672c1a2d2'
down_revision = '42155d349dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('owner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'owner')
    # ### end Alembic commands ###
