"""make model fields nullable=False

Revision ID: e53158237866
Revises: 27f444225b03
Create Date: 2023-01-18 11:03:56.768514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53158237866'
down_revision = '27f444225b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'owner',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('board', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('card', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('board', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('board', 'owner',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
